/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }

    public static void main(String[] args) {

        Android android = new Android();
        android.setName("Android Phone");
        android.setBrand("Iphone");
        android.setColor("Blue");
        android.setMessageLimit(5);
        System.out.println("name :"+ android.getName() + ", color :" + android.getColor() + ", brand :" + android.getBrand());






//        System.out.println(new App().getGreeting());
    }
}
